# Generated by Django 2.2.12 on 2020-09-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wlCaseDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('APPL_ID', models.CharField(default='', max_length=100)),
                ('ID_NO', models.CharField(default='', max_length=80)),
            ],
        ),
    ]
